-- Ejecuta este archivo en el SQL Editor de Supabase.
-- Supabase Auth administra usuarios, contrasenas hasheadas y login con Google.

create schema if not exists private;

create table if not exists public.roles (
  id smallint generated by default as identity primary key,
  nombre text not null unique check (nombre in ('admin', 'usuario'))
);

insert into public.roles (id, nombre)
values (1, 'admin'), (2, 'usuario')
on conflict (id) do update set nombre = excluded.nombre;

select setval(pg_get_serial_sequence('public.roles', 'id'), 2, true);

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  rol_id smallint not null default 2 references public.roles(id),
  active_session_token text,
  active_session_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.perfiles
add column if not exists active_session_token text;

alter table public.perfiles
add column if not exists active_session_started_at timestamptz;

create table if not exists public.vacaciones (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null default auth.uid() references public.perfiles(id) on delete cascade,
  fecha_inicio date not null,
  fecha_fin date not null,
  dias integer generated always as ((fecha_fin - fecha_inicio) + 1) stored,
  motivo text not null,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'aprobado', 'rechazado')),
  comentario_admin text,
  autorizado_por uuid references public.perfiles(id),
  fecha_respuesta timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vacaciones_rango_fechas_check check (fecha_fin >= fecha_inicio),
  constraint vacaciones_comentario_respuesta_check check (
    (estado = 'pendiente' and autorizado_por is null and fecha_respuesta is null)
    or (estado in ('aprobado', 'rechazado') and autorizado_por is not null and fecha_respuesta is not null)
  )
);

create index if not exists vacaciones_usuario_id_idx on public.vacaciones(usuario_id);
create index if not exists vacaciones_estado_idx on public.vacaciones(estado);
create index if not exists vacaciones_created_at_idx on public.vacaciones(created_at desc);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists perfiles_set_updated_at on public.perfiles;
create trigger perfiles_set_updated_at
before update on public.perfiles
for each row execute function private.set_updated_at();

drop trigger if exists vacaciones_set_updated_at on public.vacaciones;
create trigger vacaciones_set_updated_at
before update on public.vacaciones
for each row execute function private.set_updated_at();

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.perfiles p
    where p.id = auth.uid()
      and p.rol_id = 1
  );
$$;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  display_name text;
begin
  display_name := coalesce(
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'name',
    split_part(new.email, '@', 1),
    'Usuario'
  );

  insert into public.perfiles (id, nombre, rol_id)
  values (new.id, display_name, 2)
  on conflict (id) do nothing;

  return new;
end;
$$;

create or replace function public.start_browser_session(browser_token text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_token text;
begin
  if auth.uid() is null or browser_token is null or length(browser_token) < 16 then
    return false;
  end if;

  select p.active_session_token
  into current_token
  from public.perfiles p
  where p.id = auth.uid()
  for update;

  if not found then
    return false;
  end if;

  if current_token is not null and current_token <> browser_token then
    return false;
  end if;

  update public.perfiles
  set active_session_token = browser_token,
      active_session_started_at = now()
  where id = auth.uid();

  return true;
end;
$$;

create or replace function public.clear_browser_session(browser_token text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or browser_token is null then
    return false;
  end if;

  update public.perfiles
  set active_session_token = null,
      active_session_started_at = null
  where id = auth.uid()
    and active_session_token = browser_token;

  return true;
end;
$$;

create or replace function public.admin_update_profile(
  target_user_id uuid,
  new_nombre text,
  new_rol_id smallint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  admin_count integer;
begin
  if not private.is_admin() then
    return false;
  end if;

  if target_user_id is null
    or new_nombre is null
    or btrim(new_nombre) = ''
    or new_rol_id not in (1, 2) then
    return false;
  end if;

  if new_rol_id = 2 then
    select count(*)
    into admin_count
    from public.perfiles
    where rol_id = 1
      and id <> target_user_id;

    if admin_count = 0 then
      return false;
    end if;
  end if;

  update public.perfiles
  set nombre = btrim(new_nombre),
      rol_id = new_rol_id
  where id = target_user_id;

  return found;
end;
$$;

create or replace function public.admin_clear_user_session(target_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() or target_user_id is null then
    return false;
  end if;

  update public.perfiles
  set active_session_token = null,
      active_session_started_at = null
  where id = target_user_id;

  return found;
end;
$$;

create or replace function public.admin_list_profiles()
returns table (
  id uuid,
  email text,
  nombre text,
  rol_id smallint,
  rol_nombre text,
  active_session_started_at timestamptz,
  has_active_session boolean,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id,
    u.email::text,
    p.nombre,
    p.rol_id,
    r.nombre as rol_nombre,
    p.active_session_started_at,
    p.active_session_token is not null as has_active_session,
    p.created_at
  from public.perfiles p
  join public.roles r on r.id = p.rol_id
  left join auth.users u on u.id = p.id
  where private.is_admin()
  order by p.created_at desc;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

alter table public.roles enable row level security;
alter table public.perfiles enable row level security;
alter table public.vacaciones enable row level security;

drop policy if exists "roles visibles para autenticados" on public.roles;
create policy "roles visibles para autenticados"
on public.roles for select
to authenticated
using (true);

drop policy if exists "perfiles visibles por dueno o admin" on public.perfiles;
create policy "perfiles visibles por dueno o admin"
on public.perfiles for select
to authenticated
using (id = auth.uid() or private.is_admin());

drop policy if exists "usuarios actualizan su nombre" on public.perfiles;
create policy "usuarios actualizan su nombre"
on public.perfiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "vacaciones visibles por dueno o admin" on public.vacaciones;
create policy "vacaciones visibles por dueno o admin"
on public.vacaciones for select
to authenticated
using (usuario_id = auth.uid() or private.is_admin());

drop policy if exists "usuarios crean sus vacaciones" on public.vacaciones;
create policy "usuarios crean sus vacaciones"
on public.vacaciones for insert
to authenticated
with check (
  usuario_id = auth.uid()
  and estado = 'pendiente'
  and autorizado_por is null
  and fecha_respuesta is null
);

drop policy if exists "admins resuelven vacaciones" on public.vacaciones;
create policy "admins resuelven vacaciones"
on public.vacaciones for update
to authenticated
using (private.is_admin())
with check (private.is_admin());

revoke all on public.roles from anon, authenticated;
revoke all on public.perfiles from anon, authenticated;
revoke all on public.vacaciones from anon, authenticated;
grant usage on schema public to authenticated;
grant select on public.roles to authenticated;
grant select on public.perfiles to authenticated;
grant update (nombre) on public.perfiles to authenticated;
grant select, insert on public.vacaciones to authenticated;
grant update (estado, comentario_admin, autorizado_por, fecha_respuesta) on public.vacaciones to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;
grant execute on function public.start_browser_session(text) to authenticated;
grant execute on function public.clear_browser_session(text) to authenticated;
grant execute on function public.admin_update_profile(uuid, text, smallint) to authenticated;
grant execute on function public.admin_clear_user_session(uuid) to authenticated;
grant execute on function public.admin_list_profiles() to authenticated;

create or replace view public.vacaciones_detalle
with (security_invoker = true)
as
select
  v.id,
  v.usuario_id,
  p.nombre as usuario_nombre,
  v.fecha_inicio,
  v.fecha_fin,
  v.dias,
  v.motivo,
  v.estado,
  v.comentario_admin,
  v.autorizado_por,
  admin.nombre as autorizado_por_nombre,
  v.fecha_respuesta,
  v.created_at,
  v.updated_at
from public.vacaciones v
join public.perfiles p on p.id = v.usuario_id
left join public.perfiles admin on admin.id = v.autorizado_por;

grant select on public.vacaciones_detalle to authenticated;

-- Para convertir tu usuario en admin, reemplaza el correo:
-- update public.perfiles
-- set rol_id = 1
-- where id = (select id from auth.users where email = 'admin@correo.com');
